Feat sorting
VlaPol/TMS_Lesson_26 pull request #1
Opened 2023-04-15 19:14 UTC by VlaPol

2023-04-18 18:51 UTC, oleg-grigorijan requested changes

2023-04-18 18:51 UTC, oleg-grigorijan commented on src/main/java/by/tms/service/ShowServiceImpl.java
> +        }
Можно воспользоваться тем, что switch в новых версиях Java может быть expression'ом.
```
Comparator<Show> tmpComparator = switch (action) {
   case "byCountry" ->  Show.COMPARE_BY_COUNTRY;
   case "byYear" -> Show.COMPARE_BY_YEAR;
   case "byTitle" -> Show.COMPARE_BY_NAME;
   case "byRating" -> Show.COMPARE_BY_RATING;
   case "byCounters" -> Show.COMPARE_BY_RATES_COUNTER;
}
```

2023-04-18 18:51 UTC, oleg-grigorijan commented on src/main/java/by/tms/service/ShowServiceImpl.java
> +        }
Нарушает OCP. При добавлении каждого нового типа сортировки придётся добавлять новый if. Не говоря о том, что нужно будет не забыть это сделать

2023-04-18 18:51 UTC, oleg-grigorijan commented on src/main/java/by/tms/service/ShowServiceImpl.java
> +    public List<Show> getSortedListByChainOfRules(List<Comparator<Show>> action) throws IOException {
См. комментарий по IOException из прошлого ДЗ

2023-04-18 18:51 UTC, oleg-grigorijan commented on src/main/java/by/tms/service/ShowServiceImpl.java
> +        Comparator<Show> comparatorChain = action.get(0);
Либо нужно провалидировать, что список не должен быть пустым, либо прописать отдельное поведение для пустого списка. По условию нужно дать возможность не выбирать никакие критерии сортировки, так что второй вариант предпочтительнее

2023-04-18 18:51 UTC, oleg-grigorijan commented on src/main/java/by/tms/service/ShowServiceImpl.java
> +        }
Аналогично сортировке

2023-04-18 18:51 UTC, oleg-grigorijan commented on src/main/java/by/tms/service/ShowServiceImpl.java
Автоформатирование

2023-04-18 18:51 UTC, oleg-grigorijan commented on src/main/java/by/tms/service/ShowServiceImpl.java
> +    public List<Show> getFiltredListByChainOfRules(List<Predicate<Show>> action) throws IOException {
То же самое про IOException

2023-04-18 18:51 UTC, oleg-grigorijan commented on src/main/java/by/tms/utils/predicates/PredicateBetweenTwoRates.java
> +    public PredicateBetweenTwoRates(String query) {
В конструкторах мы принимаем наиболее близкие к предметной области типы данных. В этом случае целые числа. Если вызывающая сторона имеет число в String типе, то это её проблема привести строку к корректному типу. На уровне бизнес-логики мы не должны заботиться от этом

2023-04-18 18:51 UTC, oleg-grigorijan commented on src/main/java/by/tms/utils/predicates/PredicateBetweenTwoRatesCounters.java
> +    public PredicateBetweenTwoRatesCounters(String query) {
Парсинг на вызывающей стороне

2023-04-18 18:51 UTC, oleg-grigorijan commented on src/main/java/by/tms/service/ShowService.java
> +    List<Show> getFiltredList(String action, String query) throws IOException;
Предполагалось, что будет только общий метод наподобие
`List<Show> getShowList(List<Predicate<? super Show>> filters, List<Comparator<? super Show>> sortings)`
С помощью него можно было бы покрыть все задачи.
Точно здесь не должно быть `List<Show> getFiltredList(String action, String query)`. Это задача вызывающей стороны отпарсить ввод пользователя и привести его к типам данным, которые соответствуют бизнес-логике

2023-04-19 15:42 UTC, VlaPol commented on src/main/java/by/tms/service/ShowServiceImpl.java
> +        }
исправил

2023-04-19 15:48 UTC, VlaPol commented on src/main/java/by/tms/service/ShowServiceImpl.java
> +    public List<Show> getSortedListByChainOfRules(List<Comparator<Show>> action) throws IOException {
исправил

2023-04-19 16:00 UTC, VlaPol commented on src/main/java/by/tms/service/ShowServiceImpl.java
> +        Comparator<Show> comparatorChain = action.get(0);
исправлено

2023-04-19 16:01 UTC, VlaPol commented on src/main/java/by/tms/service/ShowServiceImpl.java
), исправил

2023-04-19 16:01 UTC, VlaPol commented on src/main/java/by/tms/service/ShowServiceImpl.java
> +    public List<Show> getFiltredListByChainOfRules(List<Predicate<Show>> action) throws IOException {
исправил

2023-04-19 16:42 UTC, VlaPol commented on src/main/java/by/tms/service/ShowServiceImpl.java
> +        }
Согласен, заменю на цикл

2023-04-25 19:53 UTC, oleg-grigorijan requested changes

2023-04-25 19:53 UTC, oleg-grigorijan commented on pom.xml
> +            <version>5.9.2</version>
scope test

2023-04-25 19:53 UTC, oleg-grigorijan commented on pom.xml
> +
Плагин для выполнения JUnit 5 тестов в процессе сборки

2023-04-25 19:53 UTC, oleg-grigorijan commented on src/test/java/by/tms/service/ShowServiceImplTest.java
Автоформатирование

2023-04-25 19:53 UTC, grigo-oleg commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
Мок репозитория вернёт значение переменной shows, как ты описал в Mockito.when(...). По твоему коду сервис возвращает тот же по адресу список, что вернул репозиторий. То есть в твою переменную returnedList попадёт тот же адрес, что и shows. shows и returnedList всегда будут равны по equals, потому что это один и тот же список. Даже если сервис промодифицирует список, что противоречит ожидаемому поведению, этот тест завершится успешно. Expected значение нужно создавать отдельно

2023-04-25 19:53 UTC, oleg-grigorijan commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        shows.add(new Film("Властелин колец: Возвращение короля", 2003,"NZ", 8.7, 551487));
Можешь повыносить объекты Series и Film в константы, чтобы не дублировать их создание в каждом тесте

2023-04-25 19:53 UTC, oleg-grigorijan commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
Всегда будут равны, потому что равны по адресу

2023-04-25 19:53 UTC, oleg-grigorijan commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
Всегда будут равны, потому что равны по адресу

2023-04-25 19:53 UTC, oleg-grigorijan commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
Всегда будут равны, потому что равны по адресу

2023-04-25 19:53 UTC, oleg-grigorijan commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
Всегда будут равны, потому что равны по адресу

2023-04-25 19:53 UTC, oleg-grigorijan commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
Всегда будут равны, потому что равны по адресу

2023-04-25 19:53 UTC, oleg-grigorijan commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
Всегда будут равны, потому что равны по адресу

2023-04-25 19:53 UTC, grigo-oleg commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
Всегда будут равны, потому что равны по адресу

2023-04-25 19:53 UTC, grigo-oleg commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
Всегда будут равны, потому что равны по адресу

2023-04-25 19:53 UTC, grigo-oleg commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        waitList.add(shows.get(2));
Желательно так не делать. Чтобы вызвать shows.get(...), мы должны знать, что shows не будет модифицирован внутри service.getFiltredListByChainOfRules(...). С точни зрения теста лучше, если мы знаем минимум о внутренней реализации тестируемой фукции. Лучше напрямую указать конкретные объекты, а не доставать их из списка, который возвращает мок репозитория

2023-04-25 19:53 UTC, grigo-oleg commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertIterableEquals(returnedList, waitList);
По идее assertEquals должно хватить, потому что будет вызван equals у java.util.List, поведение которого нас устраивает

2023-04-25 19:53 UTC, grigo-oleg commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        waitList.add(shows.get(2));
Аналогично

2023-04-25 19:53 UTC, oleg-grigorijan commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        List<Show> waitList = new ArrayList<>();
wait – это ждать, список ожидания. Ожидаемый – expected

2023-04-26 15:39 UTC, VlaPol commented on pom.xml
> +            <version>5.9.2</version>
пропустил, исправил

2023-04-26 15:43 UTC, VlaPol commented on pom.xml
> +
хм, точно его добавлял, видимо пропустил этот проект ). добавил

2023-04-26 15:43 UTC, VlaPol commented on src/test/java/by/tms/service/ShowServiceImplTest.java
поправил

2023-04-26 16:01 UTC, VlaPol commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        shows.add(new Film("Властелин колец: Возвращение короля", 2003,"NZ", 8.7, 551487));
сделано

2023-04-26 16:10 UTC, VlaPol commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        waitList.add(shows.get(2));
понял, изменил

2023-04-26 18:35 UTC, VlaPol commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
исправил

2023-04-26 18:57 UTC, VlaPol commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
исправил

2023-04-26 18:57 UTC, VlaPol commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
исправил

2023-04-26 18:57 UTC, VlaPol commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
исправил

2023-04-26 18:57 UTC, VlaPol commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
исправил

2023-04-26 18:57 UTC, VlaPol commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, returnedList);
исправил

2023-05-05 13:33 UTC, oleg-grigorijan requested changes

2023-05-05 13:33 UTC, oleg-grigorijan commented on src/main/java/by/tms/repository/TVShowRepositoryImpl.java
> +                    .toList();
Нет смысла отдельно собирать стрим в список, чтобы потом этот список превратить обратно в стрим для Stream.concat. Это будет лишнее создание промежуточных списков

2023-05-05 13:33 UTC, oleg-grigorijan commented on src/main/java/by/tms/repository/TVShowRepositoryImpl.java
> +                    .toList();
Аналогично

2023-05-05 13:33 UTC, oleg-grigorijan commented on src/main/java/by/tms/repository/TVShowRepositoryImpl.java
> +//        List<Film> filmList = filmsFileParser(FILMS_FILE_NAME);
Не оставляем закомментированный код в репозиториях

2023-05-05 14:45 UTC, oleg-grigorijan requested changes

2023-05-05 14:45 UTC, oleg-grigorijan commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        assertEquals(shows, expectedList);
Не вызывается сервис. Что вообще тестируется?)

2023-05-05 14:45 UTC, oleg-grigorijan commented on src/test/java/by/tms/service/ShowServiceImplTest.java
> +        expectedList.add(SECOND_SHOW);
На expected точно можно было бы List.of( ) использовать для краткости

2023-05-05 16:23 UTC, VlaPol commented on src/main/java/by/tms/repository/TVShowRepositoryImpl.java
> +//        List<Film> filmList = filmsFileParser(FILMS_FILE_NAME);
Да, забыл удалить. Исправил

2023-05-12 15:11 UTC, grigo-oleg approved these changes

2023-05-12 15:11 UTC, oleg-grigorijan commented on src/main/java/by/tms/repository/TVShowRepositoryImpl.java
> +                                    }))
Повыносить бы эти лямбды с десериализацией хотя бы в private методы

2023-05-12 15:11 UTC, oleg-grigorijan commented on src/main/java/by/tms/repository/TVShowRepositoryImpl.java
> +                                    }))
Фильм у тебя через конструктор создаётся и наполняется, сериал – через setter'ы. Единообразно было бы лучше.

2023-05-12 16:23 UTC, VlaPol commented on src/main/java/by/tms/repository/TVShowRepositoryImpl.java
> +                                    }))
согласен, упустил

2023-05-12 16:23 UTC, merged